/**
 * Test Vector Verification for ACT VNEXT (TLS wire format)
 *
 * Reads test vectors from draft-schlesinger-02.json and verifies:
 * - Encoding roundtrips
 * - Full protocol flow with loaded values
 *
 * Vectors are generated by: npx tsx scripts/generate-vectors.ts
 */

import { describe, it, expect, beforeAll } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import {
  ristretto255,
  generateParameters,
  verifySpendProof,
  decodeIssuanceRequest,
  decodeIssuanceResponse,
  decodeSpendProof,
  decodeRefund,
  decodeCreditToken,
  encodeIssuanceRequest,
  encodeIssuanceResponse,
  encodeSpendProof,
  encodeRefund,
  encodeCreditToken,
  toHex,
} from '../src/index-vnext.js';

/** Convert hex string to Uint8Array */
function hexToBytes(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return bytes;
}

interface TestVectors {
  description: string;
  format: string;
  ciphersuite: string;
  generated: string;
  parameters: {
    domain_separator: string;
    L: number;
  };
  seeds: {
    key_gen: string;
    issuance: string;
    spend: string;
    refund: string;
  };
  key_generation: {
    private_key: string;
    public_key: string;
  };
  issuance: {
    credit_amount: string;
    ctx: string;
    issuance_request: string;
    issuance_response: string;
    credit_token: string;
  };
  spending: {
    spend_amount: string;
    nullifier: string;
    spend_proof: string;
  };
  refund: {
    refund_amount: string;
    refund: string;
    new_nullifier: string;
    new_credit_token: string;
    remaining_balance: string;
  };
}

describe('ACT VNEXT Vector Verification', () => {
  const group = ristretto255;
  let vectors: TestVectors;

  beforeAll(() => {
    const vectorPath = path.join(import.meta.dirname, 'vectors', 'draft-schlesinger-02.json');
    vectors = JSON.parse(fs.readFileSync(vectorPath, 'utf-8')) as TestVectors;
  });

  it('loads vectors from file', () => {
    expect(vectors.format).toContain('TLS');
    expect(vectors.ciphersuite).toBe('ACT_ristretto255_SHAKE128');
  });

  describe('encoding roundtrips', () => {
    it('issuance request', () => {
      const reqBytes = hexToBytes(vectors.issuance.issuance_request);
      const req = decodeIssuanceRequest(group, reqBytes);

      expect(req.K.equals(group.identity())).toBe(false);
      expect(req.pok.length).toBeGreaterThan(0);

      const reencoded = encodeIssuanceRequest(req);
      expect(toHex(reencoded)).toBe(vectors.issuance.issuance_request);
    });

    it('issuance response', () => {
      const respBytes = hexToBytes(vectors.issuance.issuance_response);
      const resp = decodeIssuanceResponse(group, respBytes);

      expect(resp.A.equals(group.identity())).toBe(false);
      expect(resp.c).toBe(BigInt(vectors.issuance.credit_amount));

      const reencoded = encodeIssuanceResponse(group, resp);
      expect(toHex(reencoded)).toBe(vectors.issuance.issuance_response);
    });

    it('credit token', () => {
      const tokenBytes = hexToBytes(vectors.issuance.credit_token);
      const token = decodeCreditToken(group, tokenBytes);

      expect(token.c).toBe(BigInt(vectors.issuance.credit_amount));

      const reencoded = encodeCreditToken(group, token);
      expect(toHex(reencoded)).toBe(vectors.issuance.credit_token);
    });

    it('spend proof', () => {
      const proofBytes = hexToBytes(vectors.spending.spend_proof);
      const proof = decodeSpendProof(group, vectors.parameters.L, proofBytes);

      expect(proof.s).toBe(BigInt(vectors.spending.spend_amount));
      expect(toHex(proof.k.toBytes())).toBe(vectors.spending.nullifier);

      const reencoded = encodeSpendProof(group, proof);
      expect(toHex(reencoded)).toBe(vectors.spending.spend_proof);
    });

    it('refund', () => {
      const refundBytes = hexToBytes(vectors.refund.refund);
      const refund = decodeRefund(group, refundBytes);

      expect(refund.t).toBe(BigInt(vectors.refund.refund_amount));

      const reencoded = encodeRefund(group, refund);
      expect(toHex(reencoded)).toBe(vectors.refund.refund);
    });

    it('new credit token', () => {
      const tokenBytes = hexToBytes(vectors.refund.new_credit_token);
      const token = decodeCreditToken(group, tokenBytes);

      expect(token.c).toBe(BigInt(vectors.refund.remaining_balance));
      expect(toHex(token.k.toBytes())).toBe(vectors.refund.new_nullifier);

      const reencoded = encodeCreditToken(group, token);
      expect(toHex(reencoded)).toBe(vectors.refund.new_credit_token);
    });
  });

  describe('protocol verification', () => {
    it('verifies spend proof', () => {
      const params = generateParameters(
        group,
        vectors.parameters.domain_separator,
        vectors.parameters.L
      );

      // Load private key
      const skBytes = hexToBytes(vectors.key_generation.private_key);
      const sk = { x: group.scalarFromBytes(skBytes) };

      // Load and verify spend proof
      const proofBytes = hexToBytes(vectors.spending.spend_proof);
      const proof = decodeSpendProof(group, vectors.parameters.L, proofBytes);

      expect(() => verifySpendProof(params, sk, proof)).not.toThrow();
    });

    it('validates balance arithmetic', () => {
      const creditAmount = BigInt(vectors.issuance.credit_amount);
      const spendAmount = BigInt(vectors.spending.spend_amount);
      const refundAmount = BigInt(vectors.refund.refund_amount);
      const remainingBalance = BigInt(vectors.refund.remaining_balance);

      // 100 - 30 + 10 = 80
      expect(creditAmount - spendAmount + refundAmount).toBe(remainingBalance);
    });

    it('nullifier in token matches spend proof', () => {
      const tokenBytes = hexToBytes(vectors.issuance.credit_token);
      const token = decodeCreditToken(group, tokenBytes);

      expect(toHex(token.k.toBytes())).toBe(vectors.spending.nullifier);
    });

    it('new token has different nullifier (unlinkability)', () => {
      const originalTokenBytes = hexToBytes(vectors.issuance.credit_token);
      const originalToken = decodeCreditToken(group, originalTokenBytes);

      const newTokenBytes = hexToBytes(vectors.refund.new_credit_token);
      const newToken = decodeCreditToken(group, newTokenBytes);

      expect(newToken.k.equals(originalToken.k)).toBe(false);
    });
  });
});
